apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::698593245670:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-Y9Z3ZJR1LHR6
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::698593245670:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-23T06:34:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1765"
  uid: f6270dd4-9766-4e73-938d-147c8fc22483
